[View in Colaboratory](https://colab.research.google.com/github/Subarno/LearningTensorflow/blob/master/understanding_datatypes.ipynb)

In [0]:
import tensorflow as tf

This part is basically for understanding and showcasing the use of different Tensorflow datatypes.

In [3]:
a = tf.constant(2,shape=[2,2], name='a')
#a = tf.constant(2,shape=[2,2], verify_shape=True) generates error as shpe is verified

tf.InteractiveSession()

a.eval()

array([[2, 2],
       [2, 2]], dtype=int32)

Creates a constant tensor. The operations are demonstrated using Interactive session.

In [6]:
b = tf.constant([[0,1],[2,3]],name='b')

x = tf.add(a,b,name='add')

x.eval()

array([[2, 3],
       [4, 5]], dtype=int32)

In [8]:
y = tf.multiply(a,b,name='mul')
y.eval()

array([[0, 2],
       [4, 6]], dtype=int32)

Element wise addition and multiplication occurs in tensors. 

In [9]:
a = tf.zeros([2,2])
a.eval()

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [10]:
b = tf.ones([3,3],dtype=tf.int32)
b.eval()

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [12]:
a = tf.fill([2,3],8.0)
a.eval()

array([[8., 8., 8.],
       [8., 8., 8.]], dtype=float32)

In [15]:
tf.random_shuffle(x).eval()

array([[4, 5],
       [2, 3]], dtype=int32)

Different types of value assignments shown, mostly used to assign weights.

In [16]:
import numpy as np

tf.int32 == np.int32

True

Comparison between tensorflow int32 datatype and numpy int32 shown

In [29]:
a = tf.Variable(2, name='a')
b = tf.Variable([6,7], name='vector')

tf.global_variables_initializer().run()

print(a.eval())
print(b.eval())

2
[6 7]


In [4]:
W = tf.Variable(10)
W.assign(10)
W.initializer.run()
W.eval()

10

In [4]:
W = tf.Variable(2)
U = tf.Variable(2*W.initialized_value())
# U can not be initialized without initilizing W
W.initializer.run()
U.initializer.run()

print(W.eval())
print(U.eval())

2
4


Different types of tensor variable initialization shown.

In [5]:
a = tf.placeholder(tf.float32, shape=[3])
b = tf.constant([5,5,5],tf.float32)
c = a+b
print(c.eval({a:[1,2,3]}))

[6. 7. 8.]


Placeholders and input dictionary demonstrated.